// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createService = `-- name: CreateService :one
INSERT INTO services (id, shop_id, name, description, duration_minutes, price_cents, currency, active)
SELECT $1::uuid, sh.id, $2::varchar, $3::text,
       $4::integer, $5::bigint, $6::varchar, $7::boolean
FROM shops AS sh
WHERE sh.id = $8 AND sh.active = TRUE
RETURNING id, shop_id, name, description, duration_minutes, price_cents, active, created_at, updated_at, currency
`

type CreateServiceParams struct {
	ID              uuid.UUID `json:"id"`
	Name            string    `json:"name"`
	Description     string    `json:"description"`
	DurationMinutes int32     `json:"duration_minutes"`
	PriceCents      int64     `json:"price_cents"`
	Currency        string    `json:"currency"`
	Active          bool      `json:"active"`
	ShopID          uuid.UUID `json:"shop_id"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, createService,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.DurationMinutes,
		arg.PriceCents,
		arg.Currency,
		arg.Active,
		arg.ShopID,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Name,
		&i.Description,
		&i.DurationMinutes,
		&i.PriceCents,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Currency,
	)
	return i, err
}

const listActiveServicesByShopID = `-- name: ListActiveServicesByShopID :many
SELECT s.id, s.shop_id, s.name, s.description, s.duration_minutes, s.price_cents, s.active, s.created_at, s.updated_at, s.currency
FROM services AS s
INNER JOIN shops AS sh ON sh.id = s.shop_id
WHERE s.shop_id = $1 AND s.active = TRUE AND sh.active = TRUE
ORDER BY s.name ASC, s.id ASC
`

func (q *Queries) ListActiveServicesByShopID(ctx context.Context, shopID uuid.UUID) ([]Service, error) {
	rows, err := q.db.Query(ctx, listActiveServicesByShopID, shopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.Name,
			&i.Description,
			&i.DurationMinutes,
			&i.PriceCents,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
