// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getMembership = `-- name: GetMembership :one
SELECT
    user_id,
    shop_id,
    active
FROM public.shop_memberships
WHERE user_id = $1
  AND shop_id = $2
`

type GetMembershipParams struct {
	UserID uuid.UUID `json:"user_id"`
	ShopID uuid.UUID `json:"shop_id"`
}

type GetMembershipRow struct {
	UserID uuid.UUID `json:"user_id"`
	ShopID uuid.UUID `json:"shop_id"`
	Active bool      `json:"active"`
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (GetMembershipRow, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.UserID, arg.ShopID)
	var i GetMembershipRow
	err := row.Scan(&i.UserID, &i.ShopID, &i.Active)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    id,
    display_name,
    active
FROM public.users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID          uuid.UUID `json:"id"`
	DisplayName string    `json:"display_name"`
	Active      bool      `json:"active"`
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(&i.ID, &i.DisplayName, &i.Active)
	return i, err
}

const listActiveShopsByUser = `-- name: ListActiveShopsByUser :many
SELECT
    s.id AS shop_id,
    s.name,
    s.slug
FROM public.shop_memberships AS m
JOIN public.users AS u ON u.id = m.user_id
JOIN public.shops AS s ON s.id = m.shop_id
WHERE m.user_id = $1
  AND u.active = TRUE
  AND m.active = TRUE
  AND s.active = TRUE
ORDER BY s.name, s.id
`

type ListActiveShopsByUserRow struct {
	ShopID uuid.UUID `json:"shop_id"`
	Name   string    `json:"name"`
	Slug   string    `json:"slug"`
}

func (q *Queries) ListActiveShopsByUser(ctx context.Context, userID uuid.UUID) ([]ListActiveShopsByUserRow, error) {
	rows, err := q.db.Query(ctx, listActiveShopsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveShopsByUserRow{}
	for rows.Next() {
		var i ListActiveShopsByUserRow
		if err := rows.Scan(&i.ShopID, &i.Name, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipsByUser = `-- name: ListMembershipsByUser :many
SELECT
    user_id,
    shop_id,
    active
FROM public.shop_memberships
WHERE user_id = $1
ORDER BY shop_id
`

type ListMembershipsByUserRow struct {
	UserID uuid.UUID `json:"user_id"`
	ShopID uuid.UUID `json:"shop_id"`
	Active bool      `json:"active"`
}

func (q *Queries) ListMembershipsByUser(ctx context.Context, userID uuid.UUID) ([]ListMembershipsByUserRow, error) {
	rows, err := q.db.Query(ctx, listMembershipsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembershipsByUserRow{}
	for rows.Next() {
		var i ListMembershipsByUserRow
		if err := rows.Scan(&i.UserID, &i.ShopID, &i.Active); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
