// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shops.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getActiveShopIDBySlug = `-- name: GetActiveShopIDBySlug :one
SELECT id FROM shops WHERE slug = $1 AND active = TRUE
`

func (q *Queries) GetActiveShopIDBySlug(ctx context.Context, slug string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getActiveShopIDBySlug, slug)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
