// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Service struct {
	ID              uuid.UUID          `json:"id"`
	ShopID          uuid.UUID          `json:"shop_id"`
	Name            string             `json:"name"`
	Description     string             `json:"description"`
	DurationMinutes int32              `json:"duration_minutes"`
	PriceCents      int64              `json:"price_cents"`
	Active          bool               `json:"active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	Currency        string             `json:"currency"`
}

type Shop struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	Timezone  string             `json:"timezone"`
	Phone     pgtype.Text        `json:"phone"`
	Active    bool               `json:"active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
